version: '3.9'
services:

    db:
        container_name: codefirstbbdd
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "5434:5434"
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Paikon0709"
            MSSQL_PID: Express
        restart: always
    app:
        container_name: codefirstback
        build: .             
        depends_on:
            - db
        environment:
            DBServer: "db"
        ports: 
           - "44382:80"
        restart: always
    frontend:
        container_name: codefirstfront
        build:
            context: C:/Users/carlos.paredes/Desktop/CodeFirstFront/SPA
            dockerfile: C:/Users/carlos.paredes/Desktop/CodeFirstFront/SPA/Dockerfile
        depends_on:
            - app
        volumes:
            - 'C:/Users/carlos.paredes/Desktop/CodeFirstFront/SPA:/app'
            - '/app/node_modules'
        ports: 
            - 3000:3000
        restart: always
