// <auto-generated />
using System;
using CodeFirst.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirst.Migrations
{
    [DbContext(typeof(MVCContext))]
    [Migration("20211119090201_pepe11")]
    partial class pepe11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirst.DBModels.Archivo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ReferenciaID")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ReferenciaID");

                    b.ToTable("Archivo");
                });

            modelBuilder.Entity("CodeFirst.DBModels.Consulta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Consulta");
                });

            modelBuilder.Entity("CodeFirst.DBModels.Referencia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConsultaID")
                        .HasColumnType("int");

                    b.Property<string>("Ref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadesPropuesta")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ConsultaID");

                    b.ToTable("Referencia");
                });

            modelBuilder.Entity("CodeFirst.DBModels.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CodeFirst.DBModels.Archivo", b =>
                {
                    b.HasOne("CodeFirst.DBModels.Referencia", "Referencia")
                        .WithMany("Archivos")
                        .HasForeignKey("ReferenciaID");

                    b.Navigation("Referencia");
                });

            modelBuilder.Entity("CodeFirst.DBModels.Consulta", b =>
                {
                    b.HasOne("CodeFirst.DBModels.Usuario", "Usuario")
                        .WithMany("Consultas")
                        .HasForeignKey("UsuarioID");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CodeFirst.DBModels.Referencia", b =>
                {
                    b.HasOne("CodeFirst.DBModels.Consulta", null)
                        .WithMany("Referencias")
                        .HasForeignKey("ConsultaID");
                });

            modelBuilder.Entity("CodeFirst.DBModels.Consulta", b =>
                {
                    b.Navigation("Referencias");
                });

            modelBuilder.Entity("CodeFirst.DBModels.Referencia", b =>
                {
                    b.Navigation("Archivos");
                });

            modelBuilder.Entity("CodeFirst.DBModels.Usuario", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
